压缩包

diff --git a/.github/workflows/run_build.yml b/.github/workflows/run_build.yml
--- a/.github/workflows/run_build.yml
+++ b/.github/workflows/run_build.yml
@@ -83,9 +83,10 @@ jobs:
     - name: Package and export
       run: |
         cd api_server
-        mkdir -p target2/
-        cp target/release/api_server target2/ 2>/dev/null || :
-        echo "PACKAGE_PATH=$(pwd)/target2" >> $GITHUB_ENV
+        mkdir -p release/
+        cp target/release/api_server release/ 2>/dev/null || :
+        tar czvf api-server-release.tar.gz -C release .
+        echo "PACKAGE_PATH=$(pwd)/api-server-release.tar.gz" >> $GITHUB_ENV
 
     - name: Upload release package
       uses: actions/upload-artifact@v4
@@ -147,9 +148,10 @@ jobs:
         shell: bash
         run: |
           cd EasyNetwork/flutter/ || exit 1
-          mkdir -p target/ || { echo "Failed to create target/"; exit 1; }
-          cp -a build/windows/x64/runner/Release/. target/ || { echo "Failed to copy files"; exit 1; }
-          echo "PACKAGE_PATH=$(cygpath -w "$(pwd)/target")" >> $GITHUB_ENV
+          mkdir -p release/ || { echo "Failed to create release/"; exit 1; }
+          cp -a build/windows/x64/runner/Release/. release/ || { echo "Failed to copy files"; exit 1; }
+          tar czvf flutter-client-release.tar.gz -C release .
+          echo "PACKAGE_PATH=$(cygpath -w "$(pwd)/flutter-client-release.tar.gz")" >> $GITHUB_ENV
 
       - name: Upload release package
         uses: actions/upload-artifact@v4
@@ -159,7 +161,7 @@ jobs:
 
   # 发布版本
   release:
-    needs: [build-mtls-server, build-api-server, build-flutter]  # 依赖所有构建任务
+    needs: [build-mtls-server, build-api-server, build-flutter]
     if: github.ref_type == 'tag'
     runs-on: ubuntu-latest
     
